[theme]

# Primary accent for interactive elements
primaryColor = '#16A1D3'

# Background color for the main content area
backgroundColor = '#F7F7F7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#EFFFFE'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"