gsheets_url =  "https://docs.google.com/spreadsheets/d/1ZqStnyJJZkYCxWNPGchFoSPtm-iKBksEBdYx4cjIUaI/edit#gid=0"
OPENAI_API_KEY = "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"
openai_key = "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"