gsheets_url =  "https://docs.google.com/spreadsheets/d/1ZqStnyJJZkYCxWNPGchFoSPtm-iKBksEBdYx4cjIUaI/edit#gid=0"

OPENAI_API_KEY = "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"
openai_key = "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"